### ISSUE TITLE
Bootkali issue

### ISSUE THREAD

**Issue by Th3-A6add0n** [Magisk-Modules-Repo/KaliNethunter#9]
> 27|:/ # bootkali
> Mounting kali chroot...
> mount: mounting /sdcard/kali-chroot.img on /data/local/nhsystem/kali-armhf failed: No such file or directory
> /system/bin/bootkali: /data/data/com.offsec.nethunter/files/scripts/bootkali_init[268]: can't create /data/local/nhsystem/kali-armhf/etc/resolv.conf: No such file or directory
> /system/bin/bootkali: /data/data/com.offsec.nethunter/files/scripts/bootkali_init[268]: can't create /data/local/nhsystem/kali-armhf/etc/resolv.conf: No such file or directory
> /system/bin/bootkali: /data/data/com.offsec.nethunter/files/scripts/bootkali_init[268]: can't create /data/local/nhsystem/kali-armhf/etc/resolv.conf: No such file or directory
> /system/bin/bootkali: /data/data/com.offsec.nethunter/files/scripts/bootkali_init[268]: can't create /data/local/nhsystem/kali-armchroot: can't execute '/bin/bash': No such file or directory

**Comment by Th3-A6add0n** [comment]
#8 addressed the same thing but no one cared to answer for it.

**Comment by Nat-As** [comment]
can't execute '/bin/bash': No such file or directory
I'm having the same issue. Apparently using a specific different chroot solves the problem.

**Comment by Nat-As** [comment]
It looks like you may have installed the wrong chroot. Try the arm chroot if you're on android 
You can get it here : https://build.nethunter.com/kalifs/kalifs-latest/

**Comment by Th3-A6add0n** [comment]
> It looks like you may have installed the wrong chroot. Try the arm chroot if you're on android
> You can get it here : https://build.nethunter.com/kalifs/kalifs-latest/

I am installing arm64, which is for my device.

**Comment by Nat-As** [comment]
Try armhf. I had the same problem and armhf worked.

**Comment by Th3-A6add0n** [comment]
> Try armhf. I had the same problem and armhf worked.

My device's arch is arm64 based.

**Comment by Th3-A6add0n** [comment]
> Try armhf. I had the same problem and armhf worked.

It actually worked
Idk why kalifs arm64 didn't work.
